### ISSUE TITLE
ImportError: cannot import name 'PF_PACKET' from 'socket'

### ISSUE THREAD

**Issue by wadefletch** [EONRaider/Packet-Sniffer#2]
I'm on a 2020 MacBook Pro 16", and I'm unable to get `PF_PACKET` from the socket module. My googling [suggests it's not available](https://github.com/philsmd/vap11g/issues/3) [on Mac at all](https://stackoverflow.com/questions/33447440/python-using-raw-socket-with-osx). Is there some fix that could be done to enable this support? Thanks!

**Comment by EONRaider** [comment]
The current version does not support OS X or Windows but this will be implemented in the future.

**Comment by wadefletch** [comment]
Thanks, I expected as much. Could the README be amended to read something different than "any python interpreter?" I understand now that's not what you meant but it is a little misleading. Thanks again!

**Comment by SeanTolstoyevski** [comment]
I had this problem on windows.

I will use it with wsl.
